### ISSUE TITLE
http.IncomingMessage is undefined

### ISSUE THREAD

**Issue by dbrrt** [orionsoft/server-boilerplate#1]
I've got this error when I run the app, is there something else to configure?

Also got this in StackTrace : 
I20170103-22:49:40.443(1)? Exception while invoking method 'createUser' TypeError: Array.includes is not a function
I20170103-22:49:40.502(1)?     at /Users/david/server-boilerplate/node_modules/simpl-schema/dist/doValidation.js:364:15

**Comment by nicolaslopezj** [comment]
Did you install dependencies?

**Comment by dbrrt** [comment]
I followed exactly what is mentioned in the README. Can you get it working just after a clone repo ?

**Comment by nicolaslopezj** [comment]
Hm.. very strange.. I did git clone and followed the steps and it worked

**Comment by dbrrt** [comment]
Maybe that's because you've libraries globally installed that are not in the package.json, 
the authentication worked just after cloned the repo and dependencies installed?

**Comment by nicolaslopezj** [comment]
Mm maybe it's the version of node. I'm using 4.6.2

**Comment by dbrrt** [comment]
Yes maybe, I tried with 7.2.1

Edit : I cloned it again, still got the issue when I create a new user.

**Comment by nicolaslopezj** [comment]
Oh you didn't say that the error was when you created a user.. I will check

**Comment by dbrrt** [comment]
Actually, I can see the home page once the app is running.
