### ISSUE TITLE
errors on browser

### ISSUE THREAD

**Issue by comus** [orionsoft/server-boilerplate#3]
i just follow readme.

git clone
yarn
and meteor

but, it shows some error on browser

https://www.dropbox.com/s/xv9a8yqp0p6tkaq/Screenshot%202017-01-20%2015.34.47.png?dl=0

**Comment by comus** [comment]
i found these warnings and error come from orionsoft:apollo

because i created a new meteor project.
added orionsoft:apollo package
and then `yarn add graphql-server-express@^0.4.4 body-parser express graphql@^0.8.2 graphql-tools`
finally, the browser shows the same warnings and errors

**Comment by comus** [comment]
may be api.mainModule('apollo.js', `'server'`)
`createApolloServer` only for server side, right?

**Comment by nicolaslopezj** [comment]
You are right, I've fixed it now
