### ISSUE TITLE
Decorator Issues [RESOLVED]

### ISSUE THREAD

**Issue by smooJitter** [orionsoft/server-boilerplate#5]
I got the server to work.  However when began customizing and moving a few folders around, this code seems crash the server. 

```
   import { Roles } from 'meteor/nicolaslopezj:roles';
   import me from './me';
   import user from './user';

  export default {
    me,
    @Roles.action('viewUser')
    user
  };
```
Here's the error,
```
  server/imports/apollo/resolvers/Query/User/index.js:8:2: Unexpected character '@' (8:2)
```
I'm not to familiar with working with decorators.

UPDATE:  Resolved after updating .babelrc code

**Comment by nicolaslopezj** [comment]
It's great that you resolved the issue

**Comment by enzolutions** [comment]
Thanks for your guidance related with babel

I had to install the dev dependencies

```
$ npm install --save-dev babel-plugin-transform-decorators-legacy
$ npm install --save-dev babel-plugin-transform-class-properties
```
To match with the .babelrc

```
{
  "plugins": [
    "transform-decorators-legacy",
    "transform-class-properties",
  ]
}
```

BTW doesn't work in Meteor 1.6.1 😢
